apiVersion: v1
kind: ConfigMap
metadata:
  name: fp-nginx-conf
data:
  configfile: |-
    # Proxy Server port
    server {
    #  listen       443 http2 ssl;
      listen       8443;
      server_name  localhost;
    #  ssl_protocols TLSv1.2;
    #  ssl_certificate /opt/server.crt;
    #  ssl_certificate_key /opt/server.key;
    
      # DNS server
      #resolver         dns-default.openshift-dns.svc.cluster.local 8.8.8.8;
      resolver         8.8.8.8;
      resolver_timeout 5s;
      proxy_connect;
    
      location / {
          proxy_pass $scheme://$http_host$request_uri;
          proxy_set_header Host $host;
      }
    }
