apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fp-deployment
spec:
  selector:
    matchLabels:
      app: nginx-fp
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-fp
    spec:
      containers:
      - name: nginx
        image: jp.icr.io/n_sota/nginx-proxy:0.3
        ports:
        - containerPort: 443
#        - containerPort: 80
#        securityContext:
#          allowPrivilegeEscalation: true
        volumeMounts:
        - name: nginx-conf-volume
          mountPath: /usr/local/nginx/conf
        - name: nginx-conf-confd-volume
          mountPath: /usr/local/nginx/conf/conf.d
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: nginx-conf
          items:
          - key: configfile
            path: nginx.conf
          - key: mimefile
            path: mime.types
      - name: nginx-conf-confd-volume
        configMap:
          name: nginx-conf-confd
          items:
          - key: configfile
            path: default.conf
