apiVersion: v1
kind: Service
metadata:
  name: nginx-fp-deployment
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-fp
  sessionAffinity: None
  type: ClusterIP
